name: Compress Images
on:
  pull_request:
    paths:
      - 'src/assets/*.jpg'
      - 'src/assets/*.jpeg'
      - 'src/assets/*.png'
      - 'src/assets/*.webp'
jobs:
  build:
    # Only run on Pull Requests within the same repository, and not from forks.
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: '100'
          jpegProgressive: true
          pngQuality: '100'
          webpQuality: '100'